export const technologies = [
  { name: "HTML 5", icon: "/portfolio/src/assets/tech/html.png" },
  { name: "CSS 3", icon: "/portfolio/src/assets/tech/css.png" },
  { name: "JavaScript", icon: "/portfolio/src/assets/tech/javascript.png" },
  { name: "TypeScript", icon: "/portfolio/src/assets/tech/typescript.png" },
  { name: "React JS", icon: "/portfolio/src/assets/tech/reactjs.png" },
  { name: "Redux Toolkit", icon: "/portfolio/src/assets/tech/redux.png" },
  { name: "Tailwind CSS", icon: "/portfolio/src/assets/tech/tailwind.png" },
  { name: "Node JS", icon: "/portfolio/src/assets/tech/nodejs.png" },
  { name: "MongoDB", icon: "/portfolio/src/assets/tech/mongodb.png" },
  { name: "Three JS", icon: "/portfolio/src/assets/tech/threejs.svg" },
  { name: "Git", icon: "/portfolio/src/assets/tech/git.png" },
  { name: "Figma", icon: "/portfolio/src/assets/tech/figma.png" },
  { name: "Docker", icon: "/portfolio/src/assets/tech/docker.png" },
];
